// get summary
export const GET_SUMMARY_LOADING = 'GET_SUMMARY_LOADING';
export const GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESS';
export const GET_SUMMARY_FAIL = 'GET_SUMMARY_FAIL';

// finalize
export const FINALIZE_PERIOD_LOADING = 'FINALIZE_PERIOD_LOADING';
export const FINALIZE_PERIOD_SUCCESS = 'FINALIZE_PERIOD_SUCCESS';
export const FINALIZE_PERIOD_FAIL = 'FINALIZE_PERIOD_FAIL';
