// creat payment
export const CREATE = 'CREATE';
export const CREATE_PAYMENT_LOADING = 'CREATE_PAYMENT_LOADING';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_FAIL = 'CREATE_PAYMENT_FAIL';

// get info
export const GET_INFO = 'GET_INFO';
export const GET_INFO_LOADING = 'GET_INFO_LOADING';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAIL = 'GET_INFO_FAIL';

// get own past payments
export const GET_OWN_PAST_PAYMENTS_LOADING = 'GET_OWN_PAST_PAYMENTS_LOADING';
export const GET_OWN_PAST_PAYMENTS_SUCCESS = 'GET_OWN_PAST_PAYMENTS_SUCCESS';
export const GET_OWN_PAST_PAYMENTS_FAIL = 'GET_OWN_PAST_PAYMENTS_FAIL';

// get own past debt
export const GET_OWN_PAST_DEBT_LOADING = 'GET_OWN_PAST_DEBT_LOADING';
export const GET_OWN_PAST_DEBT_SUCCESS = 'GET_OWN_PAST_DEBT_SUCCESS';
export const GET_OWN_PAST_DEBT_FAIL = 'GET_OWN_PAST_DEBT_FAIL';

// get all past payments
export const GET_ALL_PAST_PAYMENTS = 'GET_ALL_PAST_PAYMENTS';
export const GET_ALL_PAST_PAYMENTS_LOADING = 'GET_ALL_PAST_PAYMENTS_LOADING';
export const GET_ALL_PAST_PAYMENTS_SUCCESS = 'GET_ALL_PAST_PAYMENTS_SUCCESS';
export const GET_ALL_PAST_PAYMENTS_FAIL = 'GET_ALL_PAST_PAYMENTS_FAIL';

// get all past payment by perID
export const GET_ALL_PAST_PAYMENTS_BY_PERID_LOADIN =
  'GET_ALL_PAST_PAYMENTS_BY_PERID_LOADIN';
export const GET_ALL_PAST_PAYMENTS_BY_PERID_SUCCESS =
  'GET_ALL_PAST_PAYMENTS_BY_PERID_SUCCESS';
export const GET_ALL_PAST_PAYMENTS_BY_PERID_FAIL =
  'GET_ALL_PAST_PAYMENTS_BY_PERID_FAIL';

// get own debt
export const GET_OWN_DEBT = 'GET_OWN_DEBT';
export const GET_OWN_DEBT_LOADING = 'GET_OWN_DEBT_LOADING';
export const GET_OWN_DEBT_SUCCESS = 'GET_OWN_DEBT_SUCCESS';
export const GET_OWN_DEBT_FAIL = 'GET_OWN_DEBT_FAIL';

// get own payments
export const GET_OWN_PAYMENTS = 'GET_OWN_PAYMENTS';
export const GET_OWN_PAYMENTS_LOADING = 'GET_OWN_PAYMENTS_LOADING';
export const GET_OWN_PAYMENTS_SUCCESS = 'GET_OWN_PAYMENTS_SUCCESS';
export const GET_OWN_PAYMENTS_FAIL = 'GET_OWN_PAYMENTS_FAIL';

// get active period
export const GET_ACTIVE_PERIOD_LOADING = 'GET_ACTIVE_PERIOD_LOADING';
export const GET_ACTIVE_PERIOD_SUCCESS = 'GET_ACTIVE_PERIOD_SUCCESS';
export const GET_ACTIVE_PERIOD_FAIL = 'GET_ACTIVE_PERIOD_FAIL';
