export const CREATE = 'CREATE';

// get info
export const GET_INFO = 'GET_INFO';
export const GET_INFO_LOADING = 'GET_INFO_LOADING';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAIL = 'GET_INFO_FAIL';

// get own past payments
export const GET_OWN_PAST_PAYMENTS_LOADING = 'GET_OWN_PAST_PAYMENTS_LOADING';
export const GET_OWN_PAST_PAYMENTS_SUCCESS = 'GET_OWN_PAST_PAYMENTS_SUCCESS';
export const GET_OWN_PAST_PAYMENTS_FAIL = 'GET_OWN_PAST_PAYMENTS_FAIL';

// get own past debt
export const GET_OWN_PAST_DEBT_LOADING = 'GET_OWN_PAST_DEBT_LOADING';
export const GET_OWN_PAST_DEBT_SUCCESS = 'GET_OWN_PAST_DEBT_SUCCESS';
export const GET_OWN_PAST_DEBT_FAIL = 'GET_OWN_PAST_DEBT_FAIL';

export const GET_OWN_DEBT = 'GET_OWN_DEBT';
export const GET_OWN_PAYMENTS = 'GET_OWN_PAYMENTS';
export const GET_ALL_PAST_PAYMENTS = 'GET_ALL_PAST_PAYMENTS';
